language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - conda create -p $HOME/py --yes pip numpy pandas requests nose numpydoc sphinx "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install pycap
  - python setup.py install
script:
- "nosetests -w test/ -v"
- "cd docs && make html"