language: python
python:
  - "2.7"
# command to install dependencies
install:
  # install numpy and pandas for full-suite testing
  - pip install --use-mirrors numpy
  - pip install --use-mirrors pandas
  - pip install --use-mirrors -r requirements.txt
  # install pycap
  - pip install -e .
script:
- "nosetests -w test/ -v"
- "cd docs && make html"
